import type { Metadata } from "next";
import "./globals.css";
import "./../../public/fonts/fonts.css";
import "./../../public/fontawesome/css/all.css"

export const metadata: Metadata = {
  title: "Blog Website",
  description: "Generated by blog website app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
